#FastAPI 

![[Pasted image 20250428174821.png]]
Ошибки запросов могут возникать из-за попыток доступа к несуществующим ресурсам, защищенным страницам без достаточных разрешений и даже из-за ошибок сервера. Ошибки в **FastAPI** образуются путем создания исключений с использованием класса `HTTPException`.

Поскольку это исключение **Python**, то его не возвращают, а вызывают. Это также означает, что если вы находитесь внутри функции, которая вызывается внутри вашей функции операции пути, и вы поднимаете `HTTPException` внутри этой функции, то она не будет выполнять остальной код в функции операции пути, а сразу завершит запрос и отправит **HTTP**-ошибку клиенту.

Класс `HTTPException` принимает три аргумента:
- `status_code`: Код состояния, который будет возвращен для этого сбоя
- `detail`: Сопроводительное сообщение для отправки клиенту
- `headers`: Необязательный параметр для ответов, требующих заголовков

В нашем текущем приложении получение несуществующей записи возвращает код статуса ответа `500` вместо кода статуса ответа `404`
![[Pasted image 20250331165709.png]]
Первым делом мы доработаем нашу функцию получения одной записи. Мы добавим возможность возврата сообщения, когда задача не может быть найдена и вызывать `HTTPException`. С его помощью мы сможем вернуть адекватный код ответа на ошибку.
```python
from fastapi import HTTPException


@app.get("/message/{message_id}")  
async def get_message(message_id: int):  
    for i in range(len(messages_db)):  
        if messages_db[i].id == message_id:  
            return messages_db[i]  
    raise HTTPException(status_code=404, detail="Message not found")
```
Теперь при попытке получить не существующую запись, мы будем получать ошибку с кодом ответа `404` и сообщением об ошибке.
![[Pasted image 20250331180358.png]]
Также мы можем добавить обработку ошибок и для других методов нашего приложения:
```python
@app.put("/message/{message_id}")  
async def update_message(message_id: int, message: str = Body()) -> str:  
    for i in range(len(messages_db)):  
        if messages_db[i].id == message_id:  
            messages_db[i].text = message  
            return 'Message {message_id} updated!'  
    raise HTTPException(status_code=404, detail='Message not found')  
  
@app.delete("/message/{message_id}")  
async def delete_message(message_id: int) -> str:  
    for i in range(len(messages_db)):  
        if messages_db[i].id == message_id:  
            current_id = messages_db[i].id  
            del messages_db[i]  
            return f'Message {current_id} deleted!'    raise HTTPException(status_code=404, detail="Message not found")
```
Также можно использовать библиотеку `from strlette import status`. В этом случае `404` код ошибки будет выглядеть следующим образом:
```http
status_code=status.HTTP_404_NOT_FOUND
```
Преимущество данного метода в том, что мы можем видеть подсказки статусов в редакторах кода:
![[Pasted image 20250331182445.png]]
**FastAPI** предоставляет тот же `starlette.status` под псевдонимом `fastapi.status` для удобства разработчика. Но его источник - это непосредственно **Starlette**.